# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 19:22
from __future__ import unicode_literals

from django.db import migrations


def combine_names(apps, schema_editor):
    Vehicle = apps.get_model('resources', 'Vehicle')
    vehicles = Vehicle.objects.select_related('manufacturer').all()
    for vehicle in vehicles:
        # import ipdb; ipdb.set_trace()
        vehicle.name = '{0} {1}'.format(vehicle.manufacturer.name, vehicle.name)
        vehicle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20161210_1849'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
