# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 19:44
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth import get_user_model


def setup_first_user(apps, schema_editor):
    User = get_user_model()
    user = User.objects.create_user('pz', email='zaroni@inatel.br', \
                                    password='Inatel2016')

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20161213_1722'),
    ]

    operations = [
        migrations.RunPython(setup_first_user)
    ]
